# Supermarket Feature Engineering exercise
[Dataset on Kaggle](https://www.kaggle.com/datasets/aungpyaeap/supermarket-sales)

In [41]:
import pandas as pd

In [42]:
supermarket_df = pd.read_csv('supermarket_sales - Sheet1.csv')

## Time for the EDA - Exploratory Data Analysis

In [43]:
supermarket_df.sample(10)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
6,355-53-5943,A,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Ewallet,413.04,4.761905,20.6520,5.8
178,407-63-8975,A,Yangon,Normal,Male,Food and beverages,73.88,6,22.1640,465.4440,3/23/2019,19:16,Ewallet,443.28,4.761905,22.1640,4.4
787,790-38-4466,C,Naypyitaw,Normal,Female,Health and beauty,10.99,5,2.7475,57.6975,1/23/2019,10:18,Credit card,54.95,4.761905,2.7475,9.3
789,497-37-6538,A,Yangon,Normal,Male,Sports and travel,58.91,7,20.6185,432.9885,1/17/2019,15:15,Ewallet,412.37,4.761905,20.6185,9.7
206,672-51-8681,C,Naypyitaw,Member,Female,Electronic accessories,66.65,9,29.9925,629.8425,1/4/2019,18:19,Credit card,599.85,4.761905,29.9925,9.7
201,542-41-0513,B,Mandalay,Member,Female,Electronic accessories,57.49,4,11.4980,241.4580,3/15/2019,11:57,Cash,229.96,4.761905,11.4980,6.6
688,173-57-2300,C,Naypyitaw,Member,Male,Sports and travel,72.88,2,7.2880,153.0480,3/13/2019,12:51,Cash,145.76,4.761905,7.2880,6.1
475,502-05-1910,A,Yangon,Normal,Male,Health and beauty,65.18,3,9.7770,205.3170,2/25/2019,20:35,Credit card,195.54,4.761905,9.7770,6.3
496,556-97-7101,C,Naypyitaw,Normal,Female,Electronic accessories,63.22,2,6.3220,132.7620,1/1/2019,15:51,Cash,126.44,4.761905,6.3220,8.5
595,470-31-3286,B,Mandalay,Normal,Male,Health and beauty,14.82,3,2.2230,46.6830,3/1/2019,11:30,Credit card,44.46,4.761905,2.2230,8.7

In [44]:
supermarket_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB

In [45]:
supermarket_df.corr(numeric_only=True)

,Unit price,Quantity,Tax 5%,Total,cogs,gross margin percentage,gross income,Rating
Unit price,1.000000,0.010778,0.633962,0.633962,0.633962,NaN,0.633962,-0.008778
Quantity,0.010778,1.000000,0.705510,0.705510,0.705510,NaN,0.705510,-0.015815
Tax 5%,0.633962,0.705510,1.000000,1.000000,1.000000,NaN,1.000000,-0.036442
Total,0.633962,0.705510,1.000000,1.000000,1.000000,NaN,1.000000,-0.036442
cogs,0.633962,0.705510,1.000000,1.000000,1.000000,NaN,1.000000,-0.036442
gross margin percentage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gross income,0.633962,0.705510,1.000000,1.000000,1.000000,NaN,1.000000,-0.036442
Rating,-0.008778,-0.015815,-0.036442,-0.036442,-0.036442,NaN,-0.036442,1.000000

In [46]:
supermarket_df['Citybranch'] = supermarket_df['City']+'-'+supermarket_df['Branch']
supermarket_df.sample(20)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Citybranch
858,234-36-2483,B,Mandalay,Normal,Male,Health and beauty,57.59,6,17.2770,362.8170,2/15/2019,13:51,Cash,345.54,4.761905,17.2770,5.1,Mandalay-B
151,584-86-7256,C,Naypyitaw,Member,Male,Sports and travel,34.56,7,12.0960,254.0160,3/11/2019,16:07,Credit card,241.92,4.761905,12.0960,7.3,Naypyitaw-C
115,225-98-1496,C,Naypyitaw,Normal,Female,Fashion accessories,27.02,3,4.0530,85.1130,3/2/2019,13:01,Credit card,81.06,4.761905,4.0530,7.1,Naypyitaw-C
905,118-62-1812,C,Naypyitaw,Member,Female,Home and lifestyle,78.38,4,15.6760,329.1960,3/24/2019,17:56,Cash,313.52,4.761905,15.6760,7.9,Naypyitaw-C
749,314-23-4520,C,Naypyitaw,Member,Male,Health and beauty,81.23,7,28.4305,597.0405,1/15/2019,20:44,Cash,568.61,4.761905,28.4305,9.0,Naypyitaw-C
852,658-66-3967,C,Naypyitaw,Normal,Male,Health and beauty,53.19,7,18.6165,390.9465,1/14/2019,15:42,Ewallet,372.33,4.761905,18.6165,5.0,Naypyitaw-C
89,318-68-5053,B,Mandalay,Normal,Female,Health and beauty,76.99,6,23.0970,485.0370,2/27/2019,17:55,Cash,461.94,4.761905,23.0970,6.1,Mandalay-B
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6,Naypyitaw-C
535,583-41-4548,C,Naypyitaw,Normal,Male,Home and lifestyle,16.67,7,5.8345,122.5245,2/7/2019,11:36,Ewallet,116.69,4.761905,5.8345,7.4,Naypyitaw-C
255,110-48-7033,B,Mandalay,Member,Male,Fashion accessories,32.62,4,6.5240,137.0040,1/29/2019,14:12,Cash,130.48,4.761905,6.5240,9.0,Mandalay-B
504,511-54-3087,B,Mandalay,Normal,Male,Sports and travel,88.45,1,4.4225,92.8725,2/25/2019,16:36,Credit card,88.45,4.761905,4.4225,9.5,Mandalay-B
786,886-77-9084,C,Naypyitaw,Normal,Male,Electronic accessories,71.89,8,28.7560,603.8760,2/19/2019,11:33,Ewallet,575.12,4.761905,28.7560,5.5,Naypyitaw-C
131,802-70-5316,A,Yangon,Member,Female,Sports and travel,92.13,6,27.6390,580.4190,3/6/2019,20:34,Cash,552.78,4.761905,27.6390,8.3,Yangon-A
264,154-74-7179,B,Mandalay,Normal,Male,Sports and travel,54.45,1,2.7225,57.1725,2/26/2019,19:24,Ewallet,54.45,4.761905,2.7225,7.9,Mandalay-B
494,437-53-3084,B,Mandalay,Normal,Male,Fashion accessories,99.89,2,9.9890,209.7690,2/26/2019,11:48,Ewallet,199.78,4.761905,9.9890,7.1,Mandalay-B
699,751-41-9720,C,Naypyitaw,Normal,Male,Home and lifestyle,97.50,10,48.7500,1023.7500,1/12/2019,16:18,Ewallet,975.00,4.761905,48.7500,8.0,Naypyitaw-C
370,201-86-2184,B,Mandalay,Member,Female,Electronic accessories,26.26,7,9.1910,193.0110,2/2/2019,19:40,Cash,183.82,4.761905,9.1910,9.9,Mandalay-B
631,655-07-2265,A,Yangon,Normal,Male,Electronic accessories,78.31,3,11.7465,246.6765,3/5/2019,16:38,Ewallet,234.93,4.761905,11.7465,5.4,Yangon-A
108,588-01-7461,C,Naypyitaw,Normal,Female,Food and beverages,33.98,9,15.2910,321.1110,3/24/2019,10:43,Cash,305.82,4.761905,15.2910,4.2,Naypyitaw-C
778,102-06-2002,C,Naypyitaw,Member,Male,Sports and travel,25.25,5,6.3125,132.5625,3/20/2019,17:52,Cash,126.25,4.761905,6.3125,6.1,Naypyitaw-C

In [47]:
customertypes = {'Normal':0, 'Member': 1}
supermarket_df['customer_code'] = supermarket_df['Customer type'].map(customertypes)
supermarket_df.sample(5)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Citybranch,customer_code
537,643-38-7867,A,Yangon,Normal,Male,Home and lifestyle,97.94,1,4.897,102.837,3/7/2019,11:44,Ewallet,97.94,4.761905,4.897,6.9,Yangon-A,0
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.291,69.111,2/22/2019,15:33,Cash,65.82,4.761905,3.291,4.1,Yangon-A,0
720,418-05-0656,B,Mandalay,Normal,Female,Fashion accessories,25.56,7,8.946,187.866,2/2/2019,20:42,Cash,178.92,4.761905,8.946,7.1,Mandalay-B,0
401,651-61-0874,C,Naypyitaw,Normal,Male,Home and lifestyle,46.22,4,9.244,194.124,3/12/2019,20:04,Credit card,184.88,4.761905,9.244,6.2,Naypyitaw-C,0
990,886-18-2897,A,Yangon,Normal,Female,Food and beverages,56.56,5,14.140,296.940,3/22/2019,19:06,Credit card,282.80,4.761905,14.140,4.5,Yangon-A,0

In [48]:
sex_codes = {'Male':0, 'Female': 1}
supermarket_df['gender_code'] = supermarket_df['Gender'].map(sex_codes)
supermarket_df.sample(5)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Citybranch,customer_code,gender_code
9,692-92-5582,B,Mandalay,Member,Female,Food and beverages,54.84,3,8.2260,172.7460,2/20/2019,13:27,Credit card,164.52,4.761905,8.2260,5.9,Mandalay-B,1,1
30,871-79-8483,B,Mandalay,Normal,Male,Fashion accessories,94.13,5,23.5325,494.1825,2/25/2019,19:39,Credit card,470.65,4.761905,23.5325,4.8,Mandalay-B,0,0
91,225-32-0908,C,Naypyitaw,Normal,Female,Sports and travel,44.86,10,22.4300,471.0300,1/26/2019,19:54,Ewallet,448.60,4.761905,22.4300,8.2,Naypyitaw-C,0,1
683,105-10-6182,A,Yangon,Member,Male,Fashion accessories,21.48,2,2.1480,45.1080,2/27/2019,12:22,Ewallet,42.96,4.761905,2.1480,6.6,Yangon-A,1,0
648,859-71-0933,C,Naypyitaw,Member,Female,Sports and travel,15.49,2,1.5490,32.5290,1/16/2019,15:10,Cash,30.98,4.761905,1.5490,6.3,Naypyitaw-C,1,1

## Encoding categoricals with many categories
One-Hot Encoding

In [49]:
from sklearn import preprocessing
enc = preprocessing.OneHotEncoder()
enc.fit(supermarket_df[['Product line']])
print(enc.categories_)
one_hot = enc.transform(supermarket_df[['Product line']]).toarray()
one_hot

[array(['Electronic accessories', 'Fashion accessories',
       'Food and beverages', 'Health and beauty', 'Home and lifestyle',
       'Sports and travel'], dtype=object)]

array([[0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.]])

In [50]:
supermarket_df[['Electronic accessories', 'Fashion accessories',
       'Food and beverages', 'Health and beauty', 'Home and lifestyle',
       'Sports and travel' ]] = one_hot

supermarket_df.sample(6)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,...,Rating,Citybranch,customer_code,gender_code,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
14,829-34-3910,A,Yangon,Normal,Female,Health and beauty,71.38,10,35.690,749.490,...,5.7,Yangon-A,0,1,0.0,0.0,0.0,1.0,0.0,0.0
957,430-02-3888,B,Mandalay,Normal,Male,Electronic accessories,46.02,6,13.806,289.926,...,7.1,Mandalay-B,0,0,1.0,0.0,0.0,0.0,0.0,0.0
555,356-44-8813,B,Mandalay,Normal,Male,Home and lifestyle,37.48,3,5.622,118.062,...,7.7,Mandalay-B,0,0,0.0,0.0,0.0,0.0,1.0,0.0
107,630-74-5166,A,Yangon,Normal,Male,Sports and travel,62.13,6,18.639,391.419,...,7.4,Yangon-A,0,0,0.0,0.0,0.0,0.0,0.0,1.0
385,525-88-7307,B,Mandalay,Member,Male,Sports and travel,75.82,1,3.791,79.611,...,5.8,Mandalay-B,1,0,0.0,0.0,0.0,0.0,0.0,1.0
981,809-46-1866,A,Yangon,Normal,Male,Health and beauty,58.15,4,11.630,244.230,...,8.4,Yangon-A,0,0,0.0,0.0,0.0,1.0,0.0,0.0

In [51]:

target = supermarket_df['Rating']
feature_list = ['Unit price','Total', 'customer_code', 'gender_code','Electronic accessories', 'Fashion accessories','Food and beverages', 'Health and beauty', 'Home and lifestyle','Sports and travel']

In [54]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(supermarket_df[feature_list], target, test_size=0.2, random_state=42)

model = LinearRegression()

model.fit(X_train ,y_train)


predicted = model.predict(X_test)

In [55]:
from sklearn import metrics
import numpy as np

mse = metrics.mean_squared_error(y_test, predicted)
print(f'MSE: {mse}')

print(f'RMSE: {np.sqrt(mse)}')

r2 = model.score(X_test, y_test)

print(f'R2 score: {r2}')

MSE: 3.10701257686935
RMSE: 1.7626719992299618
R2 score: -0.012781986071240148